apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-redis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-redis
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50